Bt 11
tel-ran-de/business-tracker-m21 pull request #15
Opened 2022-01-23 19:15 UTC by anzhelaschults

Navigation updated

2022-01-23 19:33 UTC, AR1988 commented
Пожалуйста, не дублируй имена комитов. Пусть они отображают суть изменений

2022-01-23 19:35 UTC, AR1988 requested changes

2022-01-23 19:35 UTC, AR1988 commented on src/main/webapp/src/components/About.js
> +const About = () => {
Нужно убрать из комита

2022-01-23 19:35 UTC, AR1988 commented on src/main/webapp/src/components/Projects.js
> +const Projects = () => {
Нужно убрать из комита

2022-01-23 19:35 UTC, AR1988 commented on src/main/webapp/src/components/NewProjects.js
> +const NewProjects = () => {
Нужно убрать из комита

2022-01-24 08:57 UTC, anzhelaschults commented on src/main/webapp/src/components/NewProjects.js
> +const NewProjects = () => {
ya ybrala eshe vchera, v moei versii etogo net

2022-01-24 09:01 UTC, anzhelaschults reviewed
@AR1988 updated

2022-01-24 09:43 UTC, AR1988 approved these changes

2022-01-24 10:02 UTC, merged