Bt14
tel-ran-de/business-tracker-m21 pull request #16
Opened 2022-01-23 20:49 UTC by VitaliyMakar

2022-01-23 21:08 UTC, AR1988 requested changes

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/index.css
> +  padding-top: 70px;
Зачем этот отступ в этом PR?

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/actionCreators/project_actionCreators.js
> +export const getAllProjects = () => {
Это не относится к рутам

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/RootReducer.js
> +export const RootReducer = combineReducers({
как это относится к рутам?

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/reducers/ProjectReducer.js
> +import {
Это не относится к рутам

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/actions.js
> +export const FETCH_PROJECTS = 'FETCH_PROJECTS'
Это не относится к рутам

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/vars.js
> +export const URL = 'http://localhost:8080/api'
Это не относится к рутам

2022-01-23 21:08 UTC, AR1988 commented on src/main/webapp/src/store/store.js
> +export const store = createStore(RootReducer, applyMiddleware(thunk, logger))
Это не относится к рутам

2022-01-23 21:12 UTC, AR1988 commented
Много изменений которые не входят в задачу

2022-01-24 08:54 UTC, AR1988 commented
@VitaliyMakar

2022-01-24 08:55 UTC, AR1988 commented
@VitaliyMakar Проведи так же сам code review своего решения.

2022-01-24 10:18 UTC, AR1988 submitted a review, later dismissed

2022-01-24 11:16 UTC, AR1988 approved these changes

2022-01-24 11:18 UTC, VitaliyMakar reviewed
Done review

2022-01-24 11:18 UTC, merged