implemented projects page
tel-ran-de/business-tracker-m21 pull request #21
Opened 2022-01-26 09:35 UTC by Volchitsa21

2022-01-26 10:01 UTC, AR1988 requested changes
Измени адрес и перекомить

2022-01-26 10:01 UTC, AR1988 commented on src/main/webapp/src/components/Navigation/RouterSwitch.js
> +                <Route path="/" element={<Projects/>}/>
все таки измени путь на **projects**

2022-01-27 23:36 UTC, Volchitsa21 commented on src/main/webapp/src/components/Navigation/RouterSwitch.js
> +                <Route path="/" element={<Projects/>}/>
changed path

2022-01-28 04:31 UTC, AR1988 approved these changes

2022-01-28 04:31 UTC, merged