BT-23
tel-ran-de/business-tracker-m21 pull request #34
Opened 2022-02-01 08:15 UTC by VitaliyMakar

2022-02-01 08:16 UTC, VitaliyMakar reviewed
done

2022-02-01 10:06 UTC, AR1988 requested changes

2022-02-01 10:06 UTC, AR1988 commented on src/main/webapp/src/components/Pages/Projects/Projects.js
> +            window.location.reload(false)
плохое решение перезагружать страницы в Single-page application (SPA).

Нужно обновить список который был создан при загрузки страницы с проектами. При этом не создавать новый запрос на сервер. 
Работай с массивом проектов внутри приложения. Учти что удалять нужно только в том случае если ответ 2XX

2022-02-01 10:22 UTC, VitaliyMakar commented on src/main/webapp/src/components/Pages/Projects/Projects.js
> +            window.location.reload(false)
Да! Решение плохое, на страничке нет функции рендера проектов, мапинг происходит непосредственно в html, тогда мне нужно переписать немного projects???

2022-02-02 12:51 UTC, VitaliyMakar reviewed
done

2022-02-02 15:13 UTC, AR1988 approved these changes

2022-02-02 15:16 UTC, merged