PB-26-fixes
tel-ran-de/business-tracker-m21 pull request #43
Opened 2022-02-08 22:44 UTC by VitaliyMakar

2022-02-08 22:48 UTC, VitaliyMakar reviewed
Fixes done

2022-02-08 23:18 UTC, VitaliyMakar reviewed
Fixes done

2022-02-09 07:13 UTC, AR1988 requested changes

2022-02-09 07:13 UTC, AR1988 commented on src/main/webapp/src/store/reducers/ProjectReducer.js
> +    activeProject: null
Эта переменная используется?

2022-02-09 07:13 UTC, AR1988 commented on src/main/webapp/src/components/Pages/Projects/ProjectFrom.js
> +            let ind
38можно объявить и  присвоить значение переменной на следующей строке.

2022-02-09 07:13 UTC, AR1988 commented on src/main/webapp/src/components/Pages/Projects/ProjectFrom.js
> +            let ind
Ну и нави её Index) добавь только "ex" и будет полноценное имя.
Ещё сделай проверку что удалять, если индекс `!= -1.`  Вдруг что то пойдёт не так и в списке элемента не будет по какой либо причине.

2022-02-09 22:43 UTC, closed without merging