BT-26-fix
tel-ran-de/business-tracker-m21 pull request #44
Opened 2022-02-10 19:59 UTC by VitaliyMakar

2022-02-10 20:00 UTC, VitaliyMakar commented
исправил

2022-02-10 20:01 UTC, VitaliyMakar reviewed
corrected

2022-02-11 17:57 UTC, AR1988 requested changes

2022-02-11 17:57 UTC, AR1988 commented on src/main/webapp/src/components/Pages/Projects/ProjectFrom.js
> +            formData.userIds.filter(m => m !== +e.target.value)
я не уверен на 10% что это изменит formData массив. Возможно что нужно написать `formData.userIds = formData.userIds.filter(m => m !== +e.target.value);`

![image](https://user-images.githubusercontent.com/37342319/153643495-5f508f87-7e0c-4c8e-8a88-775406b0de7e.png)

2022-02-14 10:12 UTC, AR1988 approved these changes

2022-02-14 10:12 UTC, merged